version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8383", "--workers", "4"]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile(nginx)
    ports:
      - "80:80"
    depends_on:
      - app

